#***INFORMACIÓN GENERAL***

***PRE PROCESAMIENTO DE DATOS***

(Adaptado del curso de Machine Learning de la PUCP)

“El propósito fundamental de la preparación de datos
es manipular y transformar datos sin procesar para que
que el contenido de la información contenida en el
el conjunto de datos se puede exponer o hacer más fácilmente
accesible.”

    Dorian Pyle.Data Preparation for Data Mining. 1999

Importancia de la Preparación de Datos<br>
1. Los datos reales pueden ser impuros, pueden conducir
a la extracción de patrones/reglas poco útiles.<br>
Esto se puede deber a:<br>
Datos Incompletos: falta de valores de atributos, …<br>
Datos con Ruido<br>
Datos inconsistentes (incluyendo discrepancias)<br>

2. La preparación de datos puede generar un conjunto de
datos más pequeño que el original, lo cual puede
mejorar la eficiencia del proceso de Minería de Datos.<br>
Esta actuación incluye:<br>
Selección relevante de datos: eliminando registros
duplicados, eliminando anomalías, …<br>
Reduccion de Datos: Selección de instancias, selección de características,
muestreo o selección de instancias, discretización.<br>

3. La preparación de datos genera “datos de calidad”, los
cuales pueden conducir a patrones/reglas de calidad.<br>
Por ejemplo, se puede:<br>
Recuperar información incompleta.<br>
Eliminar outliers<br>
Resolver conflictos, …<br>

    http://www.lsi.us.es/redmidas/IIreunion/trans/prepro.pdf

#***I. Obtención y descripción de los datos***

##***1.1. Conjunto de datos***

 **Problema del Titanic**<br>
Se basa en el hundimiento del barco Titanic 'Insumergible' a principios de 1912. Brinda información sobre varias personas, como sus edades, sexos, número de hermanos, puntos de embarque y si sobrevivieron o no al desastre. Con base en estas características, debe predecir si un pasajero arbitrario en el Titanic sobreviviría al hundimiento.

##***1.2. Descripción del conjunto de datos***

**Descripción del dataset:**<br><br>
PassengerId<br>
Survived (0 = No; 1 = Yes)<br>
Pclass - Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)<br>
Name - Name<br>
Sex - Sex<br>
Age - Age<br>
SibSp - Number of Siblings/Spouses Aboard<br>
Parch - Number of Parents/Children Aboard<br>
Ticket - Ticket Number<br>
Fare - Passenger Fare<br>
Cabin - Cabin<br>
Embarked - Port of Embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)<br>

##***1.3. Lectura de datos***

In [ ]:
import pandas as pd

El pre procesamiento se realiza con el titanic dataset, el cual está disponible en:
<br/>
<br/>
https://www.kaggle.com/c/titanic/data

In [ ]:
#Lectura del dataset
file_name = "Titanic.csv"

#El método "read_csv" nos permite leer un excel
dataset = pd.read_csv(file_name)

Es recomendable generar estadísticas descriptivas.

Las estadísticas descriptivas incluyen aquellas que resumen la tendencia central, la dispersión y la forma de la distribución de un conjunto de datos, excluyendo los valores de NaN.

Analiza series numéricas y de objetos, así como conjuntos de columnas DataFrame de tipos de datos mixtos. La salida variará dependiendo de lo que se proporcione.

In [ ]:
dataset.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

Verificar tamaño del dataset y la naturaleza de los datos

In [ ]:
#Tamaño del dataset
dataset.shape

(891, 12)

In [ ]:
#Vemos las primeras filas del dataset
dataset.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
847,848,0,3,"Markoff, Mr. Marin",male,35.0,0,0,349213,7.8958,NaN,C
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.0,0,0,364516,12.4750,NaN,S
316,317,1,2,"Kantor, Mrs. Sinai (Miriam Sternin)",female,24.0,1,0,244367,26.0000,NaN,S
129,130,0,3,"Ekstrom, Mr. Johan",male,45.0,0,0,347061,6.9750,NaN,S
799,800,0,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
767,768,0,3,"Mangan, Miss. Mary",female,30.5,0,0,364850,7.7500,NaN,Q
428,429,0,3,"Flynn, Mr. James",male,NaN,0,0,364851,7.7500,NaN,Q
516,517,1,2,"Lemore, Mrs. (Amelia Milley)",female,34.0,0,0,C.A. 34260,10.5000,F33,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0000,NaN,S

Revisar el tipo de dato de las columnas (variables). El tipo de dato object admite cualquier valor; por ejemplo, combinaciones de números con caracteres:

In [ ]:
#Visualizamos el tipo de dato de las columnas (variables)
dataset.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

#***II. Preprocesamiento de datos***

##***2.1. Reducción de datos***

Determinar cuantas filas (registros) existen por cada columna (variable) sin contar repeticiones. Si una columna (variable) tuviera los valores [1,1,2,3,3,4], entonces se tendrá 4 registros únicos que son [1,2,3,4]:

In [ ]:
#Cantidad de filas (registros) únicas por cada columna (variable)
dataset.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

Obtener el porcentaje de filas (registros) únicas por cada columna (variable):

In [ ]:
#Porcentaje de filas (registros) únicas por cada columna (variable). Mientras más cercano el valor a 1 significa que tiene más filas (registros) únicos
dataset.nunique() / len(dataset)

PassengerId    1.000000
Survived       0.002245
Pclass         0.003367
Name           1.000000
Sex            0.002245
Age            0.098765
SibSp          0.007856
Parch          0.007856
Ticket         0.764310
Fare           0.278339
Cabin          0.164983
Embarked       0.003367
dtype: float64

Filtrar las columnas (variables) cuyo porcentaje de filas (registros) únicos sea cercano a 1 porque lo más probable es que sean identificadores (IDs), hecho que normalmente no aporta información respecto a un objetivo como puede ser predecir los valores de una columna (variable) y por ende son considerados como ruido:

In [ ]:
#Determinar aquellas columnas (variables) que tengan un porcentaje de filas (registros) únicas por cada columna (variable) mayor al valor de 0.7
threshold = 0.7

unique_percentages = dataset.nunique() / len(dataset)

criteria = unique_percentages > threshold

columns_to_filter = unique_percentages[criteria].keys()

columns_to_filter

Index(['PassengerId', 'Name', 'Ticket'], dtype='object')

In [ ]:
#Eliminar las columnas (variables) seleccionadas en el paso anterior.
#Al aplicar "drop" obtenemos un nuevo "DataFrame", pero con el parámetro
#inplace igual a "True" podemos realizar dicha operación de eliminación y
#sobre-escribir el "DataFrame" del cual estamos eliminando con el
#nuevo "DataFrame" obtenido. El parámetro axis permite seleccionar el eje
#respecto al cual aplicar la operación "drop". Los valores válidos
#son [0 o "index"] y [1 o "columns"]
dataset.drop(columns_to_filter, axis=1, inplace=True)

dataset

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [ ]:
dataset.shape

(891, 9)

##***2.2. Limpieza y tratamiento de datos***

###***2.2.1. Eliminación de datos duplicados***

Eliminar las filas (registros) duplicadas.
<br/>
<br/>
Si ejecutáramos esto antes del paso anterior terminaríamos eliminando menos o ninguna fila (registro) debido que estas se diferenciarían entre sí mediante las columnas (variables) cuyo porcentaje de filas (registros) únicos sea cercano a 1. Por ejemplo, si tuvieramos el siguiente dataset y tratáramos de eliminar los duplicados no pasaría nada:

>A | B | C
>--- | --- | ---
>1 | h | i
>2 | j | k
>3 | h | i

Pero si elimináramos la columna (variable) A y eliminarámos duplicados obtendríamos el siguiente dataset:

>B | C
>--- | ---
>h | i
>j | k

El procedimiento de eliminar duplicados también considera los nulos para determinar si una fila (registro) es distinta o no de otra:

In [ ]:
# -- Determinar si hay datos duplicados
print(len([e for e in dataset.duplicated() if e==True]))

107

In [ ]:
#Al aplicar "drop_duplicates" obtenemos un nuevo "DataFrame", pero con el
#parámetro inplace igual a "True" podemos realizar dicha operación de
#eliminación y sobre-escribir el "DataFrame" del cual estamos eliminando con el
#nuevo "DataFrame" obtenido
dataset.drop_duplicates(keep="first", inplace=True)

#Revisar cuantas filas (registros) y columnas (variables) tiene el dataset
#después de eliminar los duplicados
dataset.shape

(784, 9)

###***2.2.2. Tratamiento de Outliers***

Los valores atípicos, son aquellos que, por ejemplo estén fuera del rango de valores permitidos para alguna característica.

###***2.2.3. Detección de inconsistencia de datos***

Revisar información incosistente. Por ejemplo, que en una misma fila en la columna "edad" se tenga el valor 7 años y en la columna "número hijos" se tenga el valor 2

###***2.2.4. Tratamiento de valores faltantes***

Determinar si existen datos faltantes o nulos, revisando para cada fila (registro)

In [ ]:
#Visualizar si las filas (registros) tienen nulos o no.
#El valor "True" indica que es nulo y "False" que no lo es
dataset.isna()

     Survived  Pclass    Sex    Age  SibSp  Parch   Fare  Cabin  Embarked
0       False   False  False  False  False  False  False   True     False
1       False   False  False  False  False  False  False  False     False
2       False   False  False  False  False  False  False   True     False
3       False   False  False  False  False  False  False  False     False
4       False   False  False  False  False  False  False   True     False
..        ...     ...    ...    ...    ...    ...    ...    ...       ...
886     False   False  False  False  False  False  False   True     False
887     False   False  False  False  False  False  False  False     False
888     False   False  False   True  False  False  False   True     False
889     False   False  False  False  False  False  False  False     False
890     False   False  False  False  False  False  False   True     False

[891 rows x 9 columns]

Determinar en cuantas filas (registros) existen vacíos en cada columna (variable) sumando todos sus valores "True" que indican nulidad:

In [ ]:
#Cantidad de filas (registros) vacías por cada columna (variable)
dataset.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [ ]:
foo = dataset.isna().sum()

for column, missing_count in foo.items():
    if missing_count != 0:
        print(column, missing_count)

Age 177
Cabin 687
Embarked 2

Obtener el porcentaje de filas (registros) vacías por cada columna (variable):

In [ ]:
#Porcentaje de filas (registros) vacías por cada columna (variable). Cuanto más cercano el valor a 1 significa que tiene más filas (registros) vacías
dataset.isna().sum() / len(dataset)

Survived    0.000000
Pclass      0.000000
Sex         0.000000
Age         0.198653
SibSp       0.000000
Parch       0.000000
Fare        0.000000
Cabin       0.771044
Embarked    0.002245
dtype: float64

Revisar las filas (registros) que cumplan con el criterio de tener nulos en la columna (variable) "Embarked":

In [ ]:
#Obtener si las filas (registros) cumplen o no con la condición de tener nulos
#en la columna (variable) "Embarked"
criteria = dataset.Embarked.isna()

criteria

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Embarked, Length: 891, dtype: bool

In [ ]:
#Visualizar las filas (registros) que cumplan con la condición de tener nulos
#en la columna (variable) "Embarked"
dataset[criteria]

     Survived  Pclass     Sex   Age  SibSp  Parch  Fare Cabin Embarked
61          1       1  female  38.0      0      0  80.0   B28      NaN
829         1       1  female  62.0      0      0  80.0   B28      NaN

Determinar que columnas (variables) son del tipo númerico y cuales son categóricas para poder usar esta información más adelante:

In [ ]:
# -- Crear listas para determinar columnas numéricas y categóricas
numeric_columns = list()
categorical_columns = list()
# -- Crear diccionarios para preparar datos que permitan la posterior
#    transformación de datos categóricos
dictionary_of_columns_with_index_to_categorical = dict()
dictionary_of_columns_with_categorical_to_index = dict()
# -- Procesar cada columna del dataset
for column in dataset:
  #Determinar si la columna (variable) es numérica o no
  if pd.api.types.is_numeric_dtype(dataset[column]):
    numeric_columns.append(column)
  else:
    #Modificar el tipo de dato de la columna (variable) mediante "astype"
    dataset[column] = dataset[column].astype("category")

    #Verificar si el tipo de dato de la columna (variable) fue transformado
    #a categórico correctamente
    if not pd.api.types.is_categorical_dtype(dataset[column]):
      raise Exception("La columna {} no se transformó correctamente a categórica".format(column))

    dictionary_of_columns_with_index_to_categorical[column] = dict()
    dictionary_of_columns_with_categorical_to_index[column] = dict()

    #Indexar los valores (categorías), sin tomar en consideración los nulos,
    #de la columna (variable) y guardamos esa información en los diccionarios
    for index, category in enumerate(dataset[column].cat.categories):
      dictionary_of_columns_with_index_to_categorical[column][index] = category
      dictionary_of_columns_with_categorical_to_index[column][category] = index

    categorical_columns.append(column)

In [ ]:
numeric_columns

['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [ ]:
categorical_columns

['Sex', 'Cabin', 'Embarked']

In [ ]:
dictionary_of_columns_with_index_to_categorical

{'Sex': {0: 'female', 1: 'male'},
 'Cabin': {0: 'A10',
  1: 'A14',
  2: 'A16',
  3: 'A19',
  4: 'A20',
  5: 'A23',
  6: 'A24',
  7: 'A26',
  8: 'A31',
  9: 'A32',
  10: 'A34',
  11: 'A36',
  12: 'A5',
  13: 'A6',
  14: 'A7',
  15: 'B101',
  16: 'B102',
  17: 'B18',
  18: 'B19',
  19: 'B20',
  20: 'B22',
  21: 'B28',
  22: 'B3',
  23: 'B30',
  24: 'B35',
  25: 'B37',
  26: 'B38',
  27: 'B39',
  28: 'B4',
  29: 'B41',
  30: 'B42',
  31: 'B49',
  32: 'B5',
  33: 'B50',
  34: 'B51 B53 B55',
  35: 'B57 B59 B63 B66',
  36: 'B58 B60',
  37: 'B69',
  38: 'B71',
  39: 'B73',
  40: 'B77',
  41: 'B78',
  42: 'B79',
  43: 'B80',
  44: 'B82 B84',
  45: 'B86',
  46: 'B94',
  47: 'B96 B98',
  48: 'C101',
  49: 'C103',
  50: 'C104',
  51: 'C106',
  52: 'C110',
  53: 'C111',
  54: 'C118',
  55: 'C123',
  56: 'C124',
  57: 'C125',
  58: 'C126',
  59: 'C128',
  60: 'C148',
  61: 'C2',
  62: 'C22 C26',
  63: 'C23 C25 C27',
  64: 'C30',
  65: 'C32',
  66: 'C45',
  67: 'C46',
  68: 'C47',
  69: 'C49',
  70: 'C50',
  71: 'C52',
  72: 'C54',
  73: 'C62 C64',
  74: 'C65',
  75: 'C68',
  76: 'C7',
  77: 'C70',
  78: 'C78',
  79: 'C82',
  80: 'C83',
  81: 'C85',
  82: 'C86',
  83: 'C87',
  84: 'C90',
  85: 'C91',
  86: 'C92',
  87: 'C93',
  88: 'C95',
  89: 'C99',
  90: 'D',
  91: 'D10 D12',
  92: 'D11',
  93: 'D15',
  94: 'D17',
  95: 'D19',
  96: 'D20',
  97: 'D21',
  98: 'D26',
  99: 'D28',
  100: 'D30',
  101: 'D33',
  102: 'D35',
  103: 'D36',
  104: 'D37',
  105: 'D45',
  106: 'D46',
  107: 'D47',
  108: 'D48',
  109: 'D49',
  110: 'D50',
  111: 'D56',
  112: 'D6',
  113: 'D7',
  114: 'D9',
  115: 'E10',
  116: 'E101',
  117: 'E12',
  118: 'E121',
  119: 'E17',
  120: 'E24',
  121: 'E25',
  122: 'E31',
  123: 'E33',
  124: 'E34',
  125: 'E36',
  126: 'E38',
  127: 'E40',
  128: 'E44',
  129: 'E46',
  130: 'E49',
  131: 'E50',
  132: 'E58',
  133: 'E63',
  134: 'E67',
  135: 'E68',
  136: 'E77',
  137: 'E8',
  138: 'F E69',
  139: 'F G63',
  140: 'F G73',
  141: 'F2',
  142: 'F33',
  143: 'F38',
  144: 'F4',
  145: 'G6',
  146: 'T'},
 'Embarked': {0: 'C', 1: 'Q', 2: 'S'}}

In [ ]:
dictionary_of_columns_with_categorical_to_index

{'Sex': {'female': 0, 'male': 1},
 'Cabin': {'A10': 0,
  'A14': 1,
  'A16': 2,
  'A19': 3,
  'A20': 4,
  'A23': 5,
  'A24': 6,
  'A26': 7,
  'A31': 8,
  'A32': 9,
  'A34': 10,
  'A36': 11,
  'A5': 12,
  'A6': 13,
  'A7': 14,
  'B101': 15,
  'B102': 16,
  'B18': 17,
  'B19': 18,
  'B20': 19,
  'B22': 20,
  'B28': 21,
  'B3': 22,
  'B30': 23,
  'B35': 24,
  'B37': 25,
  'B38': 26,
  'B39': 27,
  'B4': 28,
  'B41': 29,
  'B42': 30,
  'B49': 31,
  'B5': 32,
  'B50': 33,
  'B51 B53 B55': 34,
  'B57 B59 B63 B66': 35,
  'B58 B60': 36,
  'B69': 37,
  'B71': 38,
  'B73': 39,
  'B77': 40,
  'B78': 41,
  'B79': 42,
  'B80': 43,
  'B82 B84': 44,
  'B86': 45,
  'B94': 46,
  'B96 B98': 47,
  'C101': 48,
  'C103': 49,
  'C104': 50,
  'C106': 51,
  'C110': 52,
  'C111': 53,
  'C118': 54,
  'C123': 55,
  'C124': 56,
  'C125': 57,
  'C126': 58,
  'C128': 59,
  'C148': 60,
  'C2': 61,
  'C22 C26': 62,
  'C23 C25 C27': 63,
  'C30': 64,
  'C32': 65,
  'C45': 66,
  'C46': 67,
  'C47': 68,
  'C49': 69,
  'C50': 70,
  'C52': 71,
  'C54': 72,
  'C62 C64': 73,
  'C65': 74,
  'C68': 75,
  'C7': 76,
  'C70': 77,
  'C78': 78,
  'C82': 79,
  'C83': 80,
  'C85': 81,
  'C86': 82,
  'C87': 83,
  'C90': 84,
  'C91': 85,
  'C92': 86,
  'C93': 87,
  'C95': 88,
  'C99': 89,
  'D': 90,
  'D10 D12': 91,
  'D11': 92,
  'D15': 93,
  'D17': 94,
  'D19': 95,
  'D20': 96,
  'D21': 97,
  'D26': 98,
  'D28': 99,
  'D30': 100,
  'D33': 101,
  'D35': 102,
  'D36': 103,
  'D37': 104,
  'D45': 105,
  'D46': 106,
  'D47': 107,
  'D48': 108,
  'D49': 109,
  'D50': 110,
  'D56': 111,
  'D6': 112,
  'D7': 113,
  'D9': 114,
  'E10': 115,
  'E101': 116,
  'E12': 117,
  'E121': 118,
  'E17': 119,
  'E24': 120,
  'E25': 121,
  'E31': 122,
  'E33': 123,
  'E34': 124,
  'E36': 125,
  'E38': 126,
  'E40': 127,
  'E44': 128,
  'E46': 129,
  'E49': 130,
  'E50': 131,
  'E58': 132,
  'E63': 133,
  'E67': 134,
  'E68': 135,
  'E77': 136,
  'E8': 137,
  'F E69': 138,
  'F G63': 139,
  'F G73': 140,
  'F2': 141,
  'F33': 142,
  'F38': 143,
  'F4': 144,
  'G6': 145,
  'T': 146},
 'Embarked': {'C': 0, 'Q': 1, 'S': 2}}

Procesar las filas (registros) con nulos para las variables numéricas. Para esto podemos eliminar dichas filas (registros) o reemplazarlas con algún valor que puede ser la media, mediana, moda.
<br/>
<br/>
Un criterio que suele usarse para decidir eliminar las filas (registros) es que estas representen un porcentaje pequeño de todo el dataset:

In [ ]:
#Porcentaje de filas (registros) vacías por cada columna (variable) numérica
dataset[numeric_columns].isna().sum() / len(dataset)

Survived    0.000000
Pclass      0.000000
Age         0.198653
SibSp       0.000000
Parch       0.000000
Fare        0.000000
dtype: float64

In [ ]:
#Optar por reemplazar los nulos con algún valor para la columna (variable) "Age"
#debido que tiene un porcentaje de nulos cercano al 15% en todo el dataset.

#Usar la mediana para reemplazar los nulos de la columna 'Age'.
dataset['Age'].median()

28.0

In [ ]:
#Reemplazar los nulos con la mediana en todo el dataset y sólo se reemplazarán
#las columnas (variables) numéricas.
#Sin embargo, por formalidad se procederá a reemplazar los nulos
#con la mediana sólo de las columnas (variables) numéricas
median_of_numeric_columns = dataset[numeric_columns].median()

dataset[numeric_columns] = dataset[numeric_columns].fillna(median_of_numeric_columns)

In [ ]:
#Para reemplazar los nulos con la mediana en todo el dataset,
#tomando en cuenta que sólo se efectuará para las columnas (variables) numéricas,
#se procede con el #siguiente código que se encuentra comentado para evitar su ejecución
#dataset.fillna(dataset.median(), inplace=True)

In [ ]:
#Verificar que el porcentaje de filas (registros) vacías para las columnas (variables) numéricas es 0
dataset[numeric_columns].isna().sum() / len(dataset)

Survived    0.0
Pclass      0.0
Age         0.0
SibSp       0.0
Parch       0.0
Fare        0.0
dtype: float64

###***2.2.5. Transformación de datos categóricos***

La mayoria de modelos de aprendizaje solo entienden de datos numericos. En ese sentido, es apropiado codificar las variables categóricas del conjunto de datos. A continuación, se realiza lo especificado. Se imprimen las primeras 5 instancias del conjunto de datos con las variables categóricas codificadas a números.

In [ ]:
dictionary_of_columns_with_index_to_categorical.keys()

dict_keys(['Sex', 'Cabin', 'Embarked'])

In [ ]:
#Vemos los índices que tienen los valores (categorías) de la columna (variable)
#"Embarked" para verificar que los nulos no están indexados
dictionary_of_columns_with_index_to_categorical["Embarked"]

{0: 'C', 1: 'Q', 2: 'S'}

In [ ]:
#Vemos el diccionario anterior pero invertido
dictionary_of_columns_with_categorical_to_index["Embarked"]

{'C': 0, 'Q': 1, 'S': 2}

In [ ]:
#Revisamos los valores que posee la columna (variable) "Embarked" para confirmar
#que los nulos no fueron indexados en el diccionario
set(dataset["Embarked"])

{'C', 'Q', 'S', nan}

In [ ]:
#Visualizamos el tipo de dato de las columnas (variables) para validar que las
#no numéricas se transformaron a categóricas
dataset.dtypes

Survived       int64
Pclass         int64
Sex         category
Age          float64
SibSp          int64
Parch          int64
Fare         float64
Cabin       category
Embarked    category
dtype: object

Para aplicar el mismo procedimiento a las columnas (variables) categóricas es necesario transformarlas a numéricas:

In [ ]:
#Transformamos a números los valores (categorías) de las columnas (variables)
#categóricas sin considerar los nulos
dataset.replace(dictionary_of_columns_with_categorical_to_index, inplace=True)

dataset

     Survived  Pclass Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3   1  22.0      1      0   7.2500   NaN        2
1           1       1   0  38.0      1      0  71.2833    81        0
2           1       3   0  26.0      0      0   7.9250   NaN        2
3           1       1   0  35.0      1      0  53.1000    55        2
4           0       3   1  35.0      0      0   8.0500   NaN        2
..        ...     ...  ..   ...    ...    ...      ...   ...      ...
886         0       2   1  27.0      0      0  13.0000   NaN        2
887         1       1   0  19.0      0      0  30.0000    30        2
888         0       3   0  28.0      1      2  23.4500   NaN        2
889         1       1   1  26.0      0      0  30.0000    60        0
890         0       3   1  32.0      0      0   7.7500   NaN        1

[889 rows x 9 columns]

In [ ]:
#Visualizamos el tipo de dato de las columnas (variables)
dataset.dtypes

Survived       int64
Pclass         int64
Sex         category
Age          float64
SibSp          int64
Parch          int64
Fare         float64
Cabin       category
Embarked    category
dtype: object

Una vez transformados a números los valores (categorías) de las columnas (variables) categóricas nos encargamos de las filas (registros) con nulos:

In [ ]:
#Porcentaje de filas (registros) vacías por cada columna (variable) categórica
dataset[categorical_columns].isna().sum() / len(dataset)

Sex         0.000000
Cabin       0.772778
Embarked    0.000000
dtype: float64

In [ ]:
#Obtenemos si las filas (registros) cumplen o no con la condición de tener nulos
#en la columna (variable) "Embarked"
criteria = dataset.Embarked.isna()

#Eliminamos los nulos de la columna (variable) "Embarked"
dataset.drop(dataset[criteria].index, inplace=True)

dataset.shape

(889, 9)

In [ ]:
#Generamos una nueva lista de columnas (variables) categóricas sin contener
#"Embarked"
categorical_columns_without_embarked = categorical_columns[:]

categorical_columns_without_embarked.remove("Embarked")

categorical_columns_without_embarked

['Sex', 'Cabin']

In [ ]:
dataset.dtypes

Survived       int64
Pclass         int64
Sex         category
Age          float64
SibSp          int64
Parch          int64
Fare         float64
Cabin       category
Embarked    category
dtype: object

In [ ]:
#Reemplazamos los nulos con la mediana para todas las columnas (variables) excepto "Embarked"
median_of_categorical_columns = dataset[categorical_columns_without_embarked].median()

dataset[categorical_columns_without_embarked] = dataset[categorical_columns_without_embarked].fillna(median_of_categorical_columns)

NameError: name 'categorical_columns_without_embarked' is not defined

In [ ]:
#Verificamos que el porcentaje de filas (registros) vacías para las columnas (variables) numéricas es 0
dataset[categorical_columns].isna().sum() / len(dataset)

Sex         0.000000
Cabin       0.742967
Embarked    0.000000
dtype: float64

##***2.3. Tratamiento de desbalance de datos (Under-sampling)***

Se debe verificar si en el conjunto de datos se tiene casi la misma proporción de registros asociado a cada valor objetivo.

In [ ]:
dataset.Survived.value_counts()

Survived
0    461
1    321
Name: count, dtype: int64

##***2.4. Transformación de datos***

###***2.4.1. Evaluación para normalización o estandarización de datos***

Para que funcionen mejor muchos algoritmos de Machine Learning usados en Data Science, hay que normalizar las variables de entrada al algoritmo.<br>
Normalizar significa, en este caso, comprimir o extender los valores de la variable para que estén en un rango definido.<br>
Sin embargo, una mala aplicación de la normalización, o una elección descuidada del método de normalización puede arruinar los datos, y con ello el análisis.

##***2.5. Reducción de dimensionalidad***

La técnica de reducción de dimensionalidad se define como una forma de convertir un conjunto de datos de dimensiones elevadas en un conjunto de datos de dimensiones menores, asegurando que la información que proporciona es similar en ambos casos.<br>
Esta técnica se emplea a menudo en el aprendizaje automático para obtener un modelo predictivo más ajustado mientras se resuelven los problemas de regresión y clasificación que presentan los algoritmos.

###***2.5.1. Aplicación de Análisis de componentes principales (PCA)***

El análisis de componentes principales (PCA) es un procedimiento estadístico que utiliza una transformación ortogonal que convierte un conjunto de variables correlacionadas en un conjunto de variables no correlacionadas. PCA es la herramienta más utilizada en el análisis exploratorio de datos y en el aprendizaje automático para modelos predictivos. Además, PCA es una técnica estadística no supervisada utilizada para examinar las interrelaciones entre un conjunto de variables.